---
#
# on:
#     pull_request:
#       branches: [main]
#       types:
#         [opened, reopened]
#

name: "[REUSABLE] Automatic PR Labeler"
on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number
      config_file:
        required: false
        type: string
        default: './.github/auto-labeler-config.yaml'
permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Execute assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # v1.5.1
        with:
          pull-request-number: ${{ inputs.pull_request_number }}
          github-token: ${{ github.token }}
          conventional-commits: ${{ inputs.config_file }}
          maintain-labels-not-matched: true
          apply-changes: true
