---
#
# on:
#     pull_request:
#       branches: [main]
#       types:
#         [opened, reopened]
#

name: Automatic PR Labeler
on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number
      config_file:
        required: false
        type: string
        default: './.github/auto-labeler-config.yaml'
permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Execute assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # v1.5.1
        with:
          pull-request-number: ${{ inputs.pull_request_number }}
          github-token: ${{ github.token }}
          conventional-commits: ${{ inputs.config_file }}
          maintain-labels-not-matched: true
          apply-changes: true
